// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StingListManager.Data;

#nullable disable

namespace StingListManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222150745_AddJobCardGridLocation")]
    partial class AddJobCardGridLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("StingListManager.Data.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.BillingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FleetNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iccid")
                        .HasColumnType("TEXT");

                    b.Property<string>("IccidNorm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imei")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImeiNorm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNorm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumberNorm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SimNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingUnitMake")
                        .HasColumnType("TEXT");

                    b.Property<string>("VinNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveFrom");

                    b.HasIndex("ArchivedAt");

                    b.HasIndex("Company");

                    b.HasIndex("IccidNorm")
                        .IsUnique()
                        .HasFilter("\"ArchivedAt\" IS NULL AND (\"Status\" = 0 OR \"Status\" = 2) AND \"IccidNorm\" <> ''");

                    b.HasIndex("ImeiNorm")
                        .IsUnique()
                        .HasFilter("\"ArchivedAt\" IS NULL AND (\"Status\" = 0 OR \"Status\" = 2) AND \"ImeiNorm\" <> ''");

                    b.HasIndex("RegistrationNorm");

                    b.HasIndex("SerialNumberNorm")
                        .IsUnique()
                        .HasFilter("\"ArchivedAt\" IS NULL AND (\"Status\" = 0 OR \"Status\" = 2) AND \"SerialNumberNorm\" <> ''");

                    b.ToTable("BillingEntries");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.CancellationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRequestReceived")
                        .HasColumnType("TEXT");

                    b.Property<string>("FleetNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobCardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MakeModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitModel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateRequestReceived");

                    b.HasIndex("Registration");

                    b.ToTable("CancellationEntries");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNorm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameNorm")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.ClientQuoteSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLiveTracking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StingFmCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StingPlusCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientQuoteSummaries");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.Dashcam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllocatedVehicleRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Installed")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteriorCam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsupPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RearCam")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("TransferredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferredFromRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferredToRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpgradeSteps")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehicle")
                        .HasColumnType("TEXT");

                    b.Property<string>("WifiPassword")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AllocatedVehicleRegistration");

                    b.HasIndex("SerialNumber");

                    b.ToTable("Dashcams");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.JobCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FleetNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("GridLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iccid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imei")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobCardNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingUnitMake")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VinNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobCardNumber")
                        .IsUnique();

                    b.HasIndex("QuoteId");

                    b.HasIndex("Registration");

                    b.HasIndex("Status");

                    b.ToTable("JobCards");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountExVat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FleetNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iccid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imei")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludesAppLiveTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludesPanicButton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuoteNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Registration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingUnitMake")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VinNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("QuoteNumber")
                        .IsUnique();

                    b.HasIndex("Registration");

                    b.HasIndex("Status");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.QuoteLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludesAppLiveTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludesPanicButton")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVatExempt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LineTotalExVat")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPriceExVat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteLineItems");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.SdCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DashcamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledInVehicleRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("DashcamId", "SlotNumber");

                    b.ToTable("SdCards", t =>
                        {
                            t.HasCheckConstraint("CK_SdCards_SlotNumber", "\"SlotNumber\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("StingListManager.Data.Entities.JobCard", b =>
                {
                    b.HasOne("StingListManager.Data.Entities.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.QuoteLineItem", b =>
                {
                    b.HasOne("StingListManager.Data.Entities.Quote", "Quote")
                        .WithMany("LineItems")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.SdCard", b =>
                {
                    b.HasOne("StingListManager.Data.Entities.Dashcam", "Dashcam")
                        .WithMany("SdCards")
                        .HasForeignKey("DashcamId");

                    b.Navigation("Dashcam");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.Dashcam", b =>
                {
                    b.Navigation("SdCards");
                });

            modelBuilder.Entity("StingListManager.Data.Entities.Quote", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
