org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
TECH_API_BASE_URL=http://192.168.3.79:5075
FIREBASE_ENABLED=true
FIREBASE_API_KEY=AIzaSyBAJyt4ov1nMPnUkwO-xhzZBx5Id1DVmuU
FIREBASE_APP_ID=1:176241387132:android:3aa3763a3cf345a58c4bf9
FIREBASE_PROJECT_ID=ca-sting-list-app
FIREBASE_STORAGE_BUCKET=capitaltracking.firebasestorage.app
